# Basic system installation before the cluster installation
---
- name: Test Playbook
  hosts: rpi_cluster
  become: yes

  tasks: 
  - name: Copy MOTD to remote host
    ansible.builtin.template:
      src: "{{ template_dir }}/motd.j2"
      dest: /etc/motd
