# Basic system installation before the cluster installation
---
- name: Basic System Installation
  hosts: rpi_cluster
  become: true

  tasks:
    - name: Copy MOTD to remote host
      ansible.builtin.template:
        src: "{{ template_dir }}/motd.j2"
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

    - name: Install Base Packages
      ansible.builtin.apt:
        name:
          - vim
          - byobu
        state: present
