# Playbook for distributing Deployments on Docker Swarm or Docker Compose
---
- name: Docker Deployments
  hosts: rpi_cluster
  gather_facts: true
  become: true

  tasks:
    # Joplin
    - name: Set a Joplin compose direcotry
      set_fact:
        joplin_dir: "/home/ansible/docker-compose/joplin/"
    
    - name: Create Joplin directory
      ansible.builtin.file:
        path: {{ ansible_facts['joplin_dir'] }}
        state: directory
        mode: '0644'

    - name: Copy compose-files for joplin
      ansible.builtin.template:
        src: "{{ item[0] }}"
        dest: "{{ ansible_facts['joplin_dir'] }}{{ item[1] }}"
        owner: ansible
        group: ansible
        mode: '0400'
      loop:
        - ["{{ template_dir }}/compose-files/joplin/docker-compose.yaml.j2", "docker-compose.yaml"]
        - ["{{ template_dir }}/compose-files/joplin/nginx.conf.j2", "nginx.conf"]

    - name: Run docker compose up for joplin
      when: ansible_facts['nodename'] == "leonardo"
      ansible.builtin.shell:
        cmd: docker compose up -d
        chdir: {{ ansible_facts['joplin_dir'] }}
