# Master Playbook to controll other playbooks on the raspberry pi cluster
---
- name: Master Playbook
  hosts: rpi_cluster
  gather_facts: false

- name: System basic configuration
  ansible.builtin.import_playbook: base.yaml
