# Master Playbook to controll other playbooks on the raspberry pi cluster
---
- name: Master Playbook
  hosts: rpi_cluster
  gather_facts: false

- name: System basic configuration
  ansible.builtin.import_playbook: base.yaml

- name: Install Docker Dependencies
  ansible.builtin.import_playbook: docker.yaml

- name: Setup Docker Swarm
  ansible.builtin.import_playbook: docker-swarm.yaml
